

get http://localhost:8080/tareas?asignado=yo
Content-Type: application/json

###
post http://localhost:8080/iniciar
Content-Type: application/json

{
  "id": "1234",
  "author": "yo",
  "url": "yo.geocities.org/myfunnyarticle"
}

###
post http://localhost:8080/revisar
Content-Type: application/json

{
  "id": "8414675f-c3b4-11e9-9fa3-843a4b00acdc",
   "status": true
}
